### ISSUE TITLE
Custom scrolling

### ISSUE THREAD

**Issue by mwbernard** [eliseco/samplersite#35]
I spent a while investigating custom scrolling / custom scroll bars, and didn’t have great results. There are a few options for packages but they all seem to be either very outdated or have very few downloads which just seems like a bad option. I tried two of the more promising ones, but both were super buggy and screwed up the inner components’ layout.

I think it makes the most sense to use Chrome's custom scrollbar utilities to style the regular scrollbars how we like, and for firefox just accept that they will look like standard scrollbars. It may not be ideal, but it seems like the safest and most stable option, and we can still have custom styled elements for many site visitors (chrome)

@eliseco

**Comment by eliseco** [comment]
This seems totally reasonable, let's move forward with this strategy! On the design side I've been lobbying to minimize scrollbars on the page layouts anyway (only the sample card areas in project pages are scrollbar I think) - biggest question is the cards themselves and whether standard scrollbars even fit on the cards in firefox..
